# Generated by Django 3.0.8 on 2020-10-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luntan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelTable(
            name='users',
            table='db_users',
        ),
    ]
