# Generated by Django 3.0.8 on 2020-10-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luntan', '0002_auto_20201005_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
